{
 "title": "CCQ / Pods (Check if your client qualifies for legal aid)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace = \"$namespace\"}, ingress)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace='$namespace',container='api'}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace='$namespace', unit='byte'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace='$namespace', unit='byte'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='$namespace',container='api'}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace='$namespace', unit='core'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace='$namespace',unit='core'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "avg by(pod_name) (rate(container_network_receive_bytes_total{namespace='$namespace'}[$__rate_interval]))/1024",
     "legendFormat": "Avg Bytes Recv/sec"
    },
    {
     "expr": "avg by(pod_name) (rate(container_network_transmit_bytes_total{namespace='$namespace'}[$__rate_interval]))/1024",
     "legendFormat": "Avg Bytes Sent/sec"
    }
   ]
  }
 ]
}